version: '3'
services:
  web:
    build: web
    container_name: misp_web
    image: misp:latest
    env_file: .env
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    networks:
      bridge:
        ipv4_address: 172.18.1.2
    cap_add:
      - SYS_NICE
      - CAP_SYS_RAWIO
      - CAP_NET_RAW
    volumes:
      - /dev/urandom:/dev/random
      - /sys/fs/cgroup/:/sys/fs/cgroup:ro
      - ${DATA_DIR}/misp_web:/var/www/MISP
    environment:
      - MYSQL_HOST=${MYSQL_HOST}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MISP_ADMIN_EMAIL=${MISP_ADMIN_EMAIL}
      - MISP_ADMIN_PASSPHRASE=${MISP_ADMIN_PASSPHRASE}
      - MISP_BASEURL=${MISP_BASEURL}
      - POSTFIX_RELAY_HOST=${POSTFIX_RELAY_HOST}
      - TIMEZONE=${TIMEZONE}
    entrypoint: "wait-for-it.sh -t 0 -h db -p 3306 -- /run.sh"
  db:
    container_name: misp_db
    image: mariadb:latest
    env_file: .env
    restart: unless-stopped
    ports:
      - "3306:3306"
    networks:
      bridge:
        ipv4_address: 172.18.1.3
    volumes:
      - ${DATA_DIR}/misp_db:/var/lib/mysql
    cap_add:
      - SYS_NICE
      - CAP_SYS_RAWIO
      - CAP_NET_RAW
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
networks:
  bridge:
    ipam:
      config:
        - subnet: 172.18.1.0/24

